version: '2'
services:
  web:
    build: build
    restart: always
    links:
      - db:my-mysql
    ports:
      - "80:80"
  db:
    image: mysql:5.6
    restart: always
    ports: 
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: 'webvulscan'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
